### ISSUE TITLE
custom component support removed in esphome

### ISSUE THREAD

**Issue by bagges** [PaulSchulz/esphome-esp32s3#1]
Do you consider to lift this to external components as esphome removed the support of custom components?

Reference: https://esphome.io/guides/contributing#a-note-about-custom-components

As workaround I added this to the yaml. At least it compiles, I was not able to do a full test yet.

```
external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
```
